language: node_js
node_js:
  - "6"
  - "8"
  - "10"

sudo: false

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mail@victorquinn.com
    - GITHUB_REPO: victorquinn/dynasty
    - GIT_SOURCE: _docpress

script:
  - ./node_modules/.bin/docpress build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"]; then ./node_modules/.bin/git-update-ghpages -e; fi
